
################################################################################################
# Ricordatevi di inserire entity_id corretta >----- entity_id: humidifier.zhimi_humidifier_ca4 #
# ricordatevi di inserire il corretto notify per le notifiche, di default e' notify.telegram   #
################################################################################################


homeassistant:
  customize:
    sensor.humidifier_turn_off_timer_value:
      icon: mdi:clock
    sensor.humidifier_timers_stop_hours:
      icon: mdi:timer
    script.turn_off_humidifier_time:
      icon: mdi:timer-sand
      friendly_name: "Active Timer Humidifier Turn Off"
    
#fan:
#  - platform: xiaomi_miio_airpurifier
#    name: Xiaomi Air Humidifier
#    host: 192.168.1.24 #ip dell'umidificatore
#    token: 811exxxxxxxxxxxxxfb6c429d154171b
#    model: zhimi.humidifier.ca4

input_select:
  humidifier_fan_speed_select:
    name: Select Velocity
    options:
      - Auto
      - Low
      - Mid
      - High
    icon: mdi:fan-plus

input_number:
  airhumidifier_target_humidity:
    name: Target humidity
    min: 30
    max: 80
    step: 1

  humidifier_work_time:
    name: Start for minutes
    icon: mdi:timer-outline
    initial: 30
    min: 0
    max: 300    
    step: 30
    mode: slider


template:
  - sensor:

      - name: "airhumidifier_target_humidity"
        unique_id: "airhumidifier_target_humidity"
        state: "{{ state_attr('humidifier.zhimi_humidifier_ca4','humidity')|int(default=0) }}"
        unit_of_measurement: '%'
        icon: mdi:water-plus-outline
        device_class: humidity

      - name: "airhumidifier_time_work"
        unique_id: "airhumidifier_time_work"
        state: "{{ ((states('sensor.zhimi_humidifier_ca4_use_time')|int(default=0) /60)/60)|int(default=0) }}"
        unit_of_measurement: 'hr'
        icon: mdi:calendar-clock
      
      - name: "airhumidifier_speed"
        unique_id: "airhumidifier_speed"
        state: |
          {% if state_attr('humidifier.zhimi_humidifier_ca4','mode')|trim != 'None' %}
          {{ state_attr('humidifier.zhimi_humidifier_ca4','mode') }}
          {% else %}
            off
          {% endif %}
        icon: mdi:fan-chevron-up  

      - name: "humidifier_turn_off_timer_value"
        unique_id: "humidifier_turn_off_timer_value"
        state: >
          {{ 
            (as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%s')|int(default=0) 
             + states("input_number.humidifier_work_time")|int(default=0) * 60 ) | timestamp_custom("%H:%M",false)
          }}

      - name: "humidifier_water_level"
        unique_id: "humidifier_water_level"
        state: >
          {% set level = states('sensor.zhimi_humidifier_ca4_water_level')|int(default=0) %}
          {% if level <= 12.5 %} 1 {% elif level <= 25 %} 2 {% elif level <= 37.5 %} 3 {% elif level <= 50 %} 4
          {% elif level <= 62.5 %} 5 {% elif level <= 75 %} 6 {% elif level <= 87.5 %} 7 {% else %} 8 {% endif %}


      - name: "humidifier_vel_level"
        unique_id: "humidifier_vel_level"
        state: >
          {% set vel = state_attr('humidifier.zhimi_humidifier_ca4','mode')|trim %} 
          {% if vel == '' or vel == 'null' or vel == 'None' or vel == 'off' %} Spento {% elif vel == 'Auto' %} Auto {% elif vel == 'Mid' %} Mid {% elif vel == 'Low' %} Low
          {% else %} High {% endif %}          

      - name: "humidifier_timers_stop_hours"
        unique_id: "humidifier_timers_stop_hours"
        state: >
          {% set timers = states("input_number.humidifier_work_time")|int(default=0) %}
          {% set minutes = ((states("input_number.humidifier_work_time")|int(default=0) * 60)  | timestamp_custom("%M",false)) | int(default=0) %} 
          {% set hours= ((states("input_number.humidifier_work_time")|int(default=0) * 60)  | timestamp_custom("%H",false)) | int(default=0) %}
          {%- if timers  < 60 -%}
            {%- if timers == 1 -%}
            {{ timers }} Minuto
            {% else %}
            {{ timers }} Minuti
            {% endif %}
          {% else %}
            {%- if timers >= 60 and timers < 120 %}
            {{ hours }} ora {% if minutes != 0  %}e {{ minutes }} Min.{% endif %}
            {% else %}
            {{ hours }} ore {% if minutes != 0  %}e {{ minutes }} Min.{% endif %}
            {% endif %}
          {% endif %}  
          
          
script:
  turn_off_humidifier_time:
    mode: restart
    sequence:
      - choose:
          - conditions:
            - condition: template
              value_template: "{{ is_state('humidifier.zhimi_humidifier_ca4','on') }}"
            sequence :
              # persistent_notification.create se non avete il servizio notify telegram
              - service: notify.telegram
                data:
                  message: >
                    [🌡] Sono le {{ now().strftime("%H:%M") }} e l'Umidificatore si 
                    chiuderà tra {{ states("input_number.humidifier_work_time")|int(default=0) }} {% if states("input_number.humidifier_work_time")|int(default=0) > 1 %}Minuti{% else %}Minuto{% endif %}.
              - delay:
                  minutes: '{{ states("input_number.humidifier_work_time")|int(default=0) }}'
              - condition: template
                value_template: "{{ is_state('humidifier.zhimi_humidifier_ca4','on') }}"          
              - service: homeassistant.turn_off
                entity_id: humidifier.zhimi_humidifier_ca4
              # persistent_notification.create se non avete il servizio notify telegram
              - service: notify.telegram
                data:
                  message: >
                    {% set timers = states("input_number.humidifier_work_time")|int(default=0) %}
                    [💤] Umidificatore Spento alle ore {{ now().strftime("%H:%M") }} ed è stato acceso per {{states('sensor.humidifier_timers_stop_hours')}}
        default:
          # persistent_notification.create se non avete il servizio notify telegram
          - service: telegram.notify
            data:
              message: >
                [⚠️] Umidificatore spento, devi prima accenderlo.
                
                
automation:

# impostazione umidità desiderata

  - id: 75855824-aa2a-4bdd-b472-f9f3a67d73c8
    alias: Select target humidity by slider
    mode: restart
    trigger:
      platform: state
      entity_id: input_number.airhumidifier_target_humidity
    action:
      - service: humidifier.set_humidity
        data:
          entity_id: humidifier.zhimi_humidifier_ca4
          humidity: "{{ states('input_number.airhumidifier_target_humidity')|int(default=0) }}"

  - id: 5ddebb3e-c713-4313-a1d9-02ccbafaa628
    alias: Monitor target humidity and update slider
    mode: trigger
    trigger:
      platform: state
      entity_id: sensor.airhumidifier_target_humidity
    condition:
      - "{{ states('sensor.airhumidifier_target_humidity')|int(default=0) != 0}}"
    action:
      - service: input_number.set_value
        entity_id: input_number.airhumidifier_target_humidity
        data:
          value: "{{ state_attr('humidifier.zhimi_humidifier_ca4','humidity')|int(default=0) }}"

 ###########################################################################################
# notifica mancanza acqua

  - id: 01d9e5ee-71c3-4d21-bf10-a2d7cbef7cf3
    alias: Humidifier - Water tank Empty
    initial_state: 'true'
    mode: single
    max_exceeded: silent
    trigger:
      - platform: numeric_state
        entity_id: sensor.zhimi_humidifier_ca4_water_level
        below: 10
        above: 0
    action:
      # persistent_notification.create se non avete il servizio notify telegram
      - service: notify.telegram
        data:
          message: >
            [💧] L'Acqua nel serbatoio dell'Umidificatore si sta esaurendo. Il livello è del {{ states('sensor.airhumidifier_water_level')}}%.



# selezione velocita umidificatore

  - id: d5ee03e0-5fbd-4c14-bf5b-200a15355d8a
    alias: Humidifier - Velocity Select
    initial_state: 'true'
    mode: restart
    trigger:
      - platform: state
        entity_id: input_select.humidifier_fan_speed_select
      - platform: state
        entity_id: sensor.airhumidifier_speed
    action:
      - choose:
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'Auto' and trigger.entity_id == 'input_select.humidifier_fan_speed_select' }}"
          sequence:  
            - service: homeassistant.turn_on
              entity_id: humidifier.zhimi_humidifier_ca4
            - service: humidifier.set_mode
              data:      
                entity_id: humidifier.zhimi_humidifier_ca4
                mode: Auto
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'Low' and trigger.entity_id == 'input_select.humidifier_fan_speed_select' }}"
          sequence: 
            - service: homeassistant.turn_on
              entity_id: humidifier.zhimi_humidifier_ca4
            - service: humidifier.set_mode
              data:      
                entity_id: humidifier.zhimi_humidifier_ca4
                mode: Low
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'Mid' and trigger.entity_id == 'input_select.humidifier_fan_speed_select' }}"
          sequence: 
            - service: homeassistant.turn_on
              entity_id: humidifier.zhimi_humidifier_ca4
            - service: humidifier.set_mode
              data:      
                entity_id: humidifier.zhimi_humidifier_ca4
                mode: Mid
        - conditions:
            - condition: template
              value_template: "{{ trigger.to_state.state == 'High' and trigger.entity_id == 'input_select.humidifier_fan_speed_select' }}"
          sequence:  
            - service: homeassistant.turn_on
              entity_id: humidifier.zhimi_humidifier_ca4
            - service: humidifier.set_mode
              data:      
                entity_id: humidifier.zhimi_humidifier_ca4
                mode: High
      - choose:
        - conditions:
            - condition: template
              value_template: "{{ state_attr('humidifier.zhimi_humidifier_ca4','mode')|trim != 'None' and  trigger.entity_id == 'sensor.airhumidifier_speed' and trigger.from_state.state != 'off' }}"
          sequence:  
            - service: script.invia_notifiche_telegram_html5
              data:
                message: >-
                  {% if states('sensor.zhimi_humidifier_ca4_water_level')|int(default=0) < 10 %}
                  [💧] Il livello dell'acqua è sotto il 10%  
                   La Velocità Umidificatore sarà pre impostata in Auto!
                  {% else %}
                  [💧] Velocità Umidificatore Impostata su {{ state_attr('humidifier.zhimi_humidifier_ca4','mode')}}
                  -->{{ trigger.from_state.state }}
                  {% endif %}
            - condition: template
              value_template: "{{ states('input_select.humidifier_fan_speed_select')|trim !=  states('sensor.airhumidifier_speed') }}"
            - service: input_select.select_option
              target:
                entity_id: input_select.humidifier_fan_speed_select
              data:
                option: "{{ states('sensor.airhumidifier_speed') }}"
        
